version: '3.4'

services:
  library.api:
    image: ${DOCKER_REGISTRY-}library
    container_name: library.api 
    build:
      context: .
      dockerfile: Library.API/Dockerfile
  cache:
    image: redis
    restart: always
    ports:
     - 6379:6379

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

   
volumes:
  postgres-data: